################################################################################################
#   Copyright (c) Rowe Wilson Frederisk Holme. All rights reserved.
#   Licensed under the MIT License. See License.txt in the project root for license information.
################################################################################################
---
root: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  # ecmaVersion: 11
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/naming-convention": "warn"
  "@typescript-eslint/semi": "warn"
  "curly": "warn"
  "eqeqeq": "warn"
  "no-throw-literal": "warn"
  "no-useless-escape": "off"
  "semi": "off"
ignorePatterns:
  - "out"
  - "dist"
  - "**/*.d.ts"
  - "webpack.config.js"
